inputs validation

diff --git a/.github/workflows/aws-rds-snapshot.yaml b/.github/workflows/aws-rds-snapshot.yaml
--- a/.github/workflows/aws-rds-snapshot.yaml
+++ b/.github/workflows/aws-rds-snapshot.yaml
@@ -53,6 +53,17 @@ jobs:
     outputs:
       snapshot_arn: ${{ steps.snapshot.outputs.snapshot_arn }}
     steps:
+      - name: Validate Inputs
+        run: |
+          if [[ "${{ inputs.source_rds_identifier }}" =~ ^[[:blank:]]*$ ]]; then
+            echo "'source_rds_identifier' cannot be empty"
+            exit 2
+          done
+          if [[ "${{ inputs.source_snapshot_name }}" =~ ^[[:blank:]]*$ ]]; then
+            echo "'source_snapshot_name' cannot be empty"
+            exit 2
+          done
+
       - name: Configure Source AWS credentials
         uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
         with:
